# Site settings
title: Welcome to the personal website of Matt Halliday
email: hello@matthalliday.ca
description: > # this means to ignore newlines until "baseurl:"
  Matt Halliday is a Front End Developer at Shopify Plus in Waterloo, Ontario, Canada.
  His focus is on creating usable, accessible, and performant websites.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.matthalliday.ca" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  style: :compressed
plugins:
  - jekyll-sitemap

# Front-matter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      permalink: /entry/:title
      author: Matt Halliday
