# Site settings
title: Matt Halliday
email: hello@matthalliday.ca
description: > # this means to ignore newlines until "baseurl:"
   Matt Halliday is a Front-end developer at Barking Dog Studios in Guelph, Ontario, Canada.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://matthalliday.ca" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  style: :compressed